### ISSUE TITLE
Erreur fatal lors de l'absence de réglages

### ISSUE THREAD

**Issue by bastienho** [wyde22/cdn-tax-receipt-france#7]
PHP Fatal error:  Uncaught TypeError: `CRM_Cdntaxreceiptsfr_Utils_DownloadPdfRecuFiscaux::downloadOutputPDF()`: Argument 1 (`$messageTemplateID`) must be of type `int`, `null` given, called in _cdn-tax-receipt-france/cdntaxreceiptsfr.functions.inc_ on line **234** and defined in _cdn-tax-receipt-france/CRM/Cdntaxreceiptsfr/Utils/DownloadPdfRecuFiscaux.php_:**40**

Stack trace:

```
#0 cdn-tax-receipt-france/cdntaxreceiptsfr.functions.inc(234): CRM_Cdntaxreceiptsfr_Utils_DownloadPdfRecuFiscaux::downloadOutputPDF()
#1 cdn-tax-receipt-france/cdntaxreceiptsfr.functions.inc(81): cdntaxreceiptsfr_generateFormattedReceipt()
#2 cdn-tax-receipt-france/cdntaxreceiptsfr.functions.inc(1030): cdntaxreceiptsfr_processTaxReceipt()
#3 cdn-tax-receipt-france/CRM/Cdntaxreceiptsfr/Task/IssueAnnualTaxReceipts.php(166): cdntaxreceiptsfr_issueAnnualTaxReceipt()
#4 civicrm/CRM/Core/Form.php(641): CRM_Cdntaxreceiptsfr_Task_IssueAnnualTaxReceipts->postProcess()
#5 civicrm/CRM/Core/StateMachine.php(144): CRM_Core_Form->mainProcess()
#6 civicrm/CRM/Core/QuickForm/Action/Next.php(43): CRM_Core_StateMachine->perform()
#7 civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Next->perform()
#8 civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle()
#9 civicrm/CRM/Core/Controller.php(355): HTML_QuickForm_Page->handle()
#10 civicrm/CRM/Core/Invoke.php(322): CRM_Core_Controller->run()
#11 civicrm/CRM/Core/Invoke.php(69): CRM_Core_Invoke::runItem()
#12 civicrm/CRM/Core/Invoke.php(36): CRM_Core_Invoke::_invoke()
#13 civicrm.php(1231): CRM_Core_Invoke::invoke()
#14 wp-includes/class-wp-hook.php(324): CiviCRM_For_WordPress->invoke()
#15 wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#16 wp-includes/plugin.php(517): WP_Hook->do_action()
#17 wp-admin/admin.php(259): do_action()
#18 {main}
  thrown in cdn-tax-receipt-france/CRM/Cdntaxreceiptsfr/Utils/DownloadPdfRecuFiscaux.php on line 40
```

**Comment by wyde22** [comment]
cette erreur doit provenir car il ne doit pas avoir de modèle de message paramétré dans les settings. A la page suivante : Administrer > CiviContribute > CDN Tax Receipts

normalement sur cette version tu dois voir un menu déroulant permettant de choisir le modèle de message utilisé pour générer les reçus fiscaux. Il faut choisir ce modèle. Le modèle est créé via le fichier `Upgrader.php` (`$this->_create_message_template_recu_fiscaux_fr($email_message_recufr, $email_subject_recufr);`). Ce développement se trouve sur la branche [evol-aggregate-templaterf](https://github.com/wyde22/cdn-tax-receipt-france/compare/evol-aggregate-templaterf)

je pense que le problème doit provenir de là

pour info ce repository sera à l'avenir abandonné car les développements se feront sur l'extension officiel de CDN Tax Receipts. En mars je vais intégrer l'équipe de développmeent et je vais voir avec eux pour ajouter les fonctionnalités propre au reçus fiscaux
